import mlx.core as mx
import mlx.nn as nn

def coverage_loss(mu_net: mx.array, logvar_net: mx.array, z_target: mx.array, mask: mx.array = None) -> mx.array:
    """
    Computes the Negative Log-Likelihood (NLL) / Coverage Loss.
    Ensures that the truth point (z_target) from the God Encoder falls well
    within the probability net generated by Mamba's dynamic state.
    
    L_coverage = (z_target - mu_net)^2 / (2 * sigma_net^2) + log(sigma_net)
               = 0.5 * ( (z - mu)^2 / exp(logvar) ) + 0.5 * logvar
    """
    # Numerically stabilize logvar to prevent VAE gradient explosion
    # Mamba might predict highly confident (very negative logvar) initial steps,
    # causing var to approach 0, blowing up the gradient of mu. Limit min logvar to -5.0.
    logvar_net = mx.clip(logvar_net, -5.0, 20.0)
    
    sq_err = mx.square(z_target - mu_net)
    var = mx.exp(logvar_net)
    
    quadratic_term = sq_err / var
    nll_per_dim = 0.5 * (quadratic_term + logvar_net) # Shape: (B, L, z_dim)
    
    # Mean over dimensions
    nll_per_step = nll_per_dim.mean(axis=-1) # Shape: (B, L)
    
    if mask is not None:
        nll_per_step = nll_per_step * mask
        num_valid = mx.maximum(mask.sum(), 1)
        return nll_per_step.sum() / num_valid
        
    return nll_per_step.mean()

def momentum_continuity_loss(mu_trajectory: mx.array, mask: mx.array = None) -> mx.array:
    """
    L_momentum = 1 - cos(Delta mu_t, Delta mu_{t-1})
    """
    # mu_trajectory: (B, L, z_dim)
    B, L, _ = mu_trajectory.shape
    if L < 3:
        return mx.array(0.0)
        
    delta_mu = mu_trajectory[:, 1:, :] - mu_trajectory[:, :-1, :] # (B, L-1, z_dim)
    
    delta_t = delta_mu[:, 1:, :] # (B, L-2, z_dim)
    delta_t_minus_1 = delta_mu[:, :-1, :] # (B, L-2, z_dim)
    
    # Cosine similarity: (A dot B) / (|A| |B|)
    dot_product = (delta_t * delta_t_minus_1).sum(axis=-1)
    norm_t = mx.sqrt(mx.square(delta_t).sum(axis=-1) + 1e-8)
    norm_t_1 = mx.sqrt(mx.square(delta_t_minus_1).sum(axis=-1) + 1e-8)
    
    cos_sim = dot_product / (norm_t * norm_t_1) # Shape: (B, L-2)
    
    loss_per_step = 1.0 - cos_sim
    
    if mask is not None:
        # The mask for delta_t is the mask shifted by 2
        # If sequence is originally valid up to index K, then mask_t is valid up to K-2.
        valid_mask = mask[:, 2:]
        loss_per_step = loss_per_step * valid_mask
        num_valid = mx.maximum(valid_mask.sum(), 1)
        return loss_per_step.sum() / num_valid
        
    return loss_per_step.mean()



def decoder_reconstruction_loss(logits: mx.array, target_tokens: mx.array, mask: mx.array = None, bow_weight: float = 0.0, bow_max_n: int = 5) -> mx.array:
    """
    L_recon = Cross Entropy Loss + Optional Position-Invariant Soft N-Gram BoW Reward 
    """
    ce_loss = nn.losses.cross_entropy(logits, target_tokens, reduction='none')
    
    if mask is not None:
        ce_loss = ce_loss * mask
        num_valid = mx.maximum(mask.sum(), 1)
        ce_loss = ce_loss.sum() / num_valid
    else:
        ce_loss = ce_loss.mean()

    if bow_weight > 0.0:
        reward = ngram_bow_reward(logits, target_tokens, mask, max_n=bow_max_n)
        return ce_loss - bow_weight * reward
        
    return ce_loss

def ngram_bow_reward(logits: mx.array, target_ids: mx.array, mask: mx.array = None, max_n: int = 5) -> mx.array:
    """
    Diff-Soft N-Gram Bag-of-Words Reward with Exclusive Longest-Match Subsumption.
    """
    probs = mx.softmax(logits, axis=-1)
    B, L_pred, V = probs.shape
    L_target = target_ids.shape[1]
    
    if L_target < max_n:
        max_n = L_target

    b_idx = mx.arange(B).reshape(B, 1, 1)
    i_idx = mx.arange(L_pred).reshape(1, L_pred, 1)
    t_idx = target_ids.reshape(B, 1, L_target)
    
    M = probs[b_idx, i_idx, t_idx]
    
    M_list = [None, M]
    
    # 1. Compute Continuous Probabilities
    for n in range(2, max_n + 1):
        # M_n[b, i, t] = M_n-1[b, i, t] * M_1[b, i+n-1, t+n-1]
        M_curr = M_list[-1][:, :-1, :-1] * M[:, n-1:, n-1:]
        M_list.append(M_curr)
        
    # 2. Find Max Position-Invariant Matches
    H_list = [None]
    for n in range(1, max_n + 1):
        H_list.append(mx.max(M_list[n], axis=1)) # Shape: (B, L_t - n + 1)
        
    # 3. Deduct subsets (Exclusive Longest Match Logic)
    Exclusive_H = [None]
    for n in range(1, max_n):
        H_n = H_list[n]
        H_next = H_list[n+1]
        
        # H_next has length (L_t - n). We pad left or right to align with H_n (L_t - n + 1)
        pad_right = mx.pad(H_next, [(0,0), (0,1)])
        pad_left = mx.pad(H_next, [(0,0), (1,0)])
        
        subsumed = mx.maximum(pad_right, pad_left)
        exclusive = mx.maximum(0.0, H_n - subsumed)
        Exclusive_H.append(exclusive)
        
    Exclusive_H.append(H_list[max_n]) # Largest N-Gram cannot be subsumed
    
    total_reward = 0.0
    for n in range(2, max_n + 1):
        best_hits = Exclusive_H[n]
        if mask is not None:
            valid_mask = mask[:, n-1:]
            reward_n = (best_hits * valid_mask).sum() / mx.maximum(valid_mask.sum(), 1)
        else:
            reward_n = best_hits.mean()
            
        total_reward = total_reward + reward_n * (1.5 ** float(n))
            
    return total_reward
